version: "3.3"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb_container
    restart: unless-stopped
    
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=examv2thouraya
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: paradax/springapp:latest
    container_name: springboot_container
    restart: on-failure
    ports:
      - 5000:8083
    
    stdin_open: true
    tty: true
  
             
volumes:
  db: